### PR TITLE
Various improvements

### LINKED ISSUE #16: Some questions on useability
Well, firstly thanks for providing OffsetArrays.

I want to make it simpler/cleaner to specify `OffsetArrays` backed by standard arrays. And also use analogous syntax to standard `Arrays` for creating and typing `OffsetArrays`.

An example might be best:
```
type MyType
    x::OffsetStdVector{Int} 
    y::OffsetStdArray{Float64,2}
end

a = OffsetVector{Int}(0:5) 
b = OffsetArray{Float64}(0:12, -1:1) 
c = MyType(a, b)

a = zeros(Int, 0:5)    # [3]
b = zeros(Float64, 0:12, -1:1)    #[3]
c = MyType(a, b)
```

This can be achieved currently with something like:
```
using OffsetArrays
import OffsetArrays.OffsetVector

typealias OffsetStdVector{T}  OffsetArray{T,1,Array{T,1}}
typealias OffsetStdArray{T,N} OffsetArray{T,N,Array{T,N}}

(::Type{OffsetVector{T}}){T}(inds::UnitRange{Int}) = OffsetArray{T}(inds)
(::Type{OffsetArray{T}}){T}(inds::UnitRange{Int}...) = OffsetArray{T}(inds)

Base.zeros{N}(T::Type, inds::Base.Indices{N}) = fill!(OffsetArray{T}(inds), zero(T))
Base.zeros(T::Type, inds::UnitRange{Int}...) = zeros(T, inds)
```

Ideally `OffsetArray` could be renamed to say `OffsetGenArray`, so that standard array-backed type could be just `OffsetArray`

In any case, 
1. Could `OffsetVector` be exported?
2. Is there any problem with defining methods so that `OffsetArray{T}(inds)` can construct (similar to recommended way to construct standard arrays)?
3. Why is `zero` deprecated? using syntax as above seems quite natural to me.

### PR DESCRIPTION
**Pull request by timholy**
This adds various performance and usability enhancements (fixes #16, at least the parts that can be fixed).

It also eliminates the deprecations; I think we've had those long enough that anyone relying on the old behavior has had long enough to fix problems.

### CODE REVIEW

**Comment by timholy** [comment]
@alsam, can you please enable [attobot](https://github.com/attobot/attobot)? It only takes a couple of moments to activate it (https://github.com/attobot/attobot#usage), and it saves me some hassle.

**Comment by timholy** [comment]
(If you do the next release, I think it should be v0.3.0 since I deleted some deprecations.)

**Comment by timholy** [comment]
@alsam, any interest in moving this to [JuliaArrays](https://github.com/JuliaArrays)? I can set you up with the necessary permissions if you like that idea.

Meanwhile, I'll go ahead and tag 0.3.0 the old-fashioned way.

**Comment by alsam** [comment]
Sure @timholy, it is great idea to move the library to https://github.com/JuliaArrrays , I like it. Could you please set me up with permissions?
Thank you!

**Comment by timholy** [comment]
OK, done. I'm a little confused about what privileges are needed to transfer ownership; if you find you can't do it, then let me know and I'll try to fix it.

**Comment by alsam** [comment]
Thank you! Just joined JuliaArrays organization taking advantage of your kind invitation.

**Comment by alsam** [comment]
@timholy I've just imported from https://github.com/alsam/OffsetArrays.jl to https://github.com/JuliaArrays/OffsetArrays.jl No problems with permissions so far. 
Let me know if something has to be done with the new repository.

**Comment by alsam** [comment]
@timholy just killed  https://github.com/JuliaArrays/OffsetArrays.jl - details are here  https://github.com/JuliaLang/METADATA.jl/pull/8884
could you please add admin rights for "Transfer repository" or move it yourself? Thanks!

**Comment by timholy** [comment]
OK, try the transfer again. Sorry about the inconvenience.

**Comment by alsam** [comment]
Thank you. No problem. I've finished transfer. Could you please check if it has right access rights for you?

**Comment by timholy** [comment]
Yep, looks good! Coupled with @Evizero's PR [here](https://github.com/JuliaLang/METADATA.jl/pull/8884), we're all set. Many thanks!

**Comment by Evizero** [comment]
I am unsure, but it may be needed that someone with admin permission enables Travis under JuliaArrays (?)

**Comment by timholy** [comment]
Thanks for noticing, I checked and we see to be OK.

**Pull request merged**
